# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e647bb4a295c6a2b4bd08eb53dcdc9e38d0590a5fb2c4d58da9140c88dc642d6aee5be12c8cfa6ddc531e16cf696f712968a1bd608a741117db08840e5849544

test:
  secret_key_base: bc5b96337e92c5350dfec4389ae9c0610bc2952c68fa875fae85e2ca76016b8397b5345196a8a860f4389be63167806245ff070b23a38ea23d2fe6a495c91d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
